os: osx
language: node_js
node_js: stable
notifications:
  email:
    on_success: never
    on_failure: change
deploy:
  provider: script
  script: npm run dist
  skip_cleanup: true
  on:
    tags: true
